### ISSUE TITLE
Distroless incompatible

### ISSUE THREAD

**Issue by loopingz** [loopingz/webda.io#313]
**Describe the bug**
On a distroless image the issue is:

```
6)
    at WebdaConsole.handleCommandInternal (file:///webda/node_modules/@webda/shell/lib/console/webda.js:838:83)
    at async WebdaConsole.handleCommand (file:///webda/node_modules/@webda/shell/lib/console/webda.js:440:19)
    at async file:///webda/node_modules/@webda/shell/lib/bin/webda.js:70:22 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [
    '-c',
    '( cat /var/lib/dbus/machine-id /etc/machine-id 2> /dev/null || hostname ) | head -n 1 || :'
  ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 20,
  stdout: null,
```

**Comment by loopingz** [comment]
For this case, we can just use the `WEBDA_MACHINE_ID` env variable to avoid calling this script
