### ISSUE TITLE
New context failure crash the server

### ISSUE THREAD

**Issue by loopingz** [loopingz/webda.io#461]
```
    at async WebdaServer.newContext /serve.runfiles/_main/node_modules/.aspect_rules_js/@webda+core@3.6.0_-720304098/node_modules/@webda/core/lib/core.js:968:13)
    at async WebdaServer.newWebContext /serve.runfiles/_main/node_modules/.aspect_rules_js/@webda+core@3.6.0_-720304098/node_modules/@webda/core/lib/core.js:982:16)
    at async WebdaServer.handleRequest /serve.runfiles/_main/node_modules/.aspect_rules_js/@webda+shell@3.4.0_-465917123/node_modules/@webda/shell/lib/handlers/http.js:108:19)
```

If context init fails, the server crash

**Comment by loopingz** [comment]
The healthcheck failing was causing the issue not the server i think
